insert into upcoming_matches
(scheduled_start_day, match_id, scheduled_start, away, country, home, name, tournament_name)
values
('2016-01-24 00:00:00+0100', 1, '2016-01-24 20:11:45+0100','Molde','Norway','Rosenborg','Rosenborg-Molde','Tippeligaen');

insert into upcoming_matches
(scheduled_start_day, match_id, scheduled_start, away, country, home, name, tournament_name)
values
('2016-01-24 00:00:00+0100', 2, '2016-01-24 16:11:45+0100','OB','Denmark','FC Copenhagen','FC Copenhagen-OB','Superligaen');

insert into upcoming_matches
(scheduled_start_day, match_id, scheduled_start, away, country, home, name, tournament_name)
values
('2016-01-24 00:00:00+0100', 3, '2016-01-24 12:11:45+0100','Hobro','Denmark','Aab','Aab-Hobro','Superligaen');


insert into upcoming_matches
(scheduled_start_day, match_id, scheduled_start, away, country, home, name, tournament_name)
values
('2016-01-25 00:00:00+0100', 4, '2016-01-25 20:11:45+0100','Valencia','Spain','Getafe','Getafe-Valencia','Primera Division');

insert into upcoming_matches
(scheduled_start_day, match_id, scheduled_start, away, country, home, name, tournament_name)
values
('2016-01-25 00:00:00+0100', 5, '2016-01-25 16:11:45+0100','Real Madrid','Spain','Sevilla','Sevilla-Real Madrid','Primera Division');

insert into upcoming_matches
(scheduled_start_day, match_id, scheduled_start, away, country, home, name, tournament_name)
values
('2016-01-25 00:00:00+0100', 6, '2016-01-25 12:11:45+0100','Napoli','Italy','Juventus','Juventus-Napoli','Serie A');
